spring:
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
  profiles:
    active: prod
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: vashenko49
    data: classpath:data.sql
    initialization-mode: always
server:
  port: 9000