spring:
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
  profiles:
    active: prod
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:postgresql://ruby.db.elephantsql.com/psoieywg
    driver-class-name: org.postgresql.Driver
    username: psoieywg
    password: 7oUI78gvyQBpe7zw3-oiQGFK7ypHEcD1
    data: classpath:data.sql
    initialization-mode: always
server:
  port: 9000